language: java
sudo: true
before_install:
- chmod +x mvnw
deploy:
  provider: heroku
  api_key:
    secure: EYT41TuBSqSRlX/i9+PTpGab1gXev13U51VVWWHPy4UyMmPIfXc9xCEOfJDS/Ww80+cuQIdt3tySyQNMuDh2GHKR41UDal9/wLxilnSiDqs9Jxrka3ucaOzO7J52bqSDYJ9D3ESCH0FwM1dWdURC88JM1hVenxoJj5A/Wf3XCX3r2sLZjBAOX8GPotdgbVTrBAV0afsyLl9cRLLOF72ylx7FgumN65+RCdFhUq9YZhtkUty53KrXg1E6j0N2IvXqpHIMU19JYE5zOPpdUQn3UuG575YCNqs8qPey2TW+LLw5fHCFkz24/j1V+0RSIGloQWk5pnNAufxdYjtkr1/qW6CwoYH5lJpMb9NckOcnAW2xfL2aDLtTHSfngEiDDymJUrqeB9qJKBvA5NoT+6QJxdY88wQi+Chf/tTuMwsItHxYnTNXs4fM9betp89ygNUUUxye1L9MD+YcoybFcpL8tbOdbt5VZ17cCs0c0VhtNR8kdpVeOXHYYt1s8hO/+WuOYB1KLDOIrv/FMTqz8ExPU64deLu/FbrQJ3gm05OrwWYfmFt9HPdTuv4VRBEbEd3zv59j80FGrFvyWpwjOqGmaLgd/QPLEDLpQ2EdP7Opm/xgNhf2f1Nil+LSobTWchP02bmJ2EZy6aFYBpMPEAP1Gj3yuuQzgwOOUrVZ9cK6QtA=
