language: java
sudo: true
before_install:
- chmod +x mvnw
deploy:
  provider: heroku
  api_key:
    secure: VJC7g7no53bIgrQLhENTcJb2Qsz1HnjQGj4fXqHbMfacUvAr+nq/FqN0ckvDtOi9T5OxB+WeBP/Q4S3MzBhq/KCkEPJGeFAKUbbE6FmXONcEF7wNKbY05PX4mPmpWUvRdV7QrPYZ6qJyJzherL4dsF/pJssmgMeLCbJJstKRHYAbz9C8vosuXy2sTz+tklW7BZVitnEafQJeYD0++bny9+tYsX8ycfwF8P59Xdv936Jye7JHZ1Rho7TOg9WMQ96El1cNoW5jP4EfC4kp3CU3sS7jk5TnDZUF5Mn6eR8n2BT5La19cjweVmYVc/XYrjSdj01oaBVs+8lxTPM7lXilcfGiZIl2VP1g47IEEwrrek7S7aLxxJRKaB3NSWGuFW/TE+0uYELsqqu2RUaBcBD1xtfUq16Xdmv/T6z3u1TTqfYeqnxvBLH/dZhRPVoTH8EBC02mdyHxe3kIo4cI2/gmrv3V+KAiTtrG5WCKPASjMTXD6UyS2re9nTuDV1+WKMACC2R2wC4m8EdKjS4dcFmPsLyoXTrNWgrCGyKFc33VPh69rLMpa3yg6KlJK59RpI8g50tAFoNGwdlxqbgGdH9Rbl3DexH+iIz7652mMhytxKJZpfguwtpovhdRpJPP1Zk7zJK90BIAWUVrC/ITroY/GJv/J/uqyFF0zJEZAftPjmg=
