language: java
sudo: true
before_install:
- chmod +x mvnw
deploy:
  provider: heroku
  api_key:
    secure: xYCjovTyVPRsrbUlLs1k+5L5FfA7BjTELRVt5hfsUeRBJSnXMl2oDKxfTmDJ+0etkqYYLmEkXBUHhVEo9T0cblbB8uhT/0HzbMtU4a/AicmTWlqrLatrp2LvJYjwR/jGkjObA8uAA72XsIRlRcAdlEG1/ndX8Mk0AbW/TMwhiiYGiJcypYvpfSkZ3XhC6RYGveWgk7pVK34R07TNjkhi3VAuoXB8WCC6oZPR3Sb/fRPWw3oQVpvHLpOlgDAEE379rIm1/FKuovQ4YTuc9PEOKDVtuGgSTVUBkx0EIi7dhfRzDzk61HrL5h0+PHcrxHqgqKzw8pMH5J1KB5+yUr8o/RnF3KhRrepyh3rRHh+xc+KWHwjbzZXOcw2DxQUvrW6W8d0mO5cxWjPcEZQpayYPQEyWPThIvaFBDQ0DY784y6L+XoaLP/sQbgV7DEYeNq9ks6mCdWmBV0mz2/bs2P1YgkEKl3tdog8QcHNzpdOxxpl32YAZBY/Pq1IpyLb/83YbIXxyGBLybbq/VW5m8B0EYo8+NTxtaNwT+44ith3uCkbBXc/7KioG2TkFFig6HK0/Aa5scgUxeMS8+MDAKkWAFRMHu+GiaPNvIr0WRI1O6iixBpDYfoY359vPS1H4eoM5vOhZQ+rtQRtVHC7IBsXZAhmkF+ZYpRZjuQjk3ji3gi8=
  app: lit-basin-75485
