language: java
sudo: true
before_install:
  - chmod +x mvnw
deploy:
  provider: heroku
  api_key:
    secure: FYoNlQPPI8MYFBWxf9wSDydZV+aN0XHOt4EUujWO1ldYWm3TlYMYPucqnbXBaD+WsUeEmERz8H1Pyvl+J/bu26w5a4/r0b+xpyuGEr+tJzQchNSWpeWrrke/5AipdTgAT9xzJP/COiy2PjwE/yZmeceaV6sTd/mFRzj8GRu3ijSuEv72Cr3PWrDmYBeoi1ASlUHo8xv13Q8+d2S58tnlOzyIRFFVSgGEiADCZudoFCjawRfawK63bRtID8dmTxj9Ui3nrCRjZ9sNluTUnFFYWZj96LG8ATYj6GQNBXc5cANx7SY8fxBCVs6rXfQHelqXVJ8NAt2BSx4JLtu+qkDrKv6h+OHcje6DKhpB81SiiPxBkR3chqmRznQHA5UPo3dypqBk6EwJe8ajrhFxyHk+H717ZXIKFr/5RzWKPiQXlP3ZcJZEf41NBFv0T2NM7JRYbUWPCwmnKSAJY6ZtLiGu4Gu5SqN35K3IuEKlCag0mRAG5pZ6Sqej15ho5yIRlf00deXvzTZhfCjaH5n5Eqp0ctsuWgWefEFt6Eg4vdp5Ge74tuvvcxSr0bs1JF1r0m4/zNy5XY2wNQnn8JoM3G+2S67tPaC+SbNhOwRF4PpHhvOjWZkR8Wj4See+whXLGf+fEzvQWebHWz2Vt6LI7LzPHGnzS2JCAZxgvTDA4PkHwHI=
  app: lit-basin-75485 
env:
  global:
    secure: UPEECn7tBhyeMtdHPP0RZ4JQtxabm5eRACH20y/8M/uXEbO+DbNsq5JInL7BcwhGge70ejJ7uWBI8cCb/NzoDmwXLCpyzhgO4OSiMZfEGTaN7orXKzWfxxkphRbagooYRHBDVUivWDtSipevxbpp5txXpGsYZpfUyVCVjDVmvXanWCQkJ/h+YQSyR5QTe1CaK37jXHHsBfVIjPvZli3A6Sp2flBRxbMRaqVUGjuHcLNrXnR1E8XD5hMjOhuEaiT3D9lYhE7aooh8j0PwPRys95F3nXIpO6qeFh4fzuNwKN3l6nwEiELjUvrjsfAPtih5Uo6kZduB+A8WSlv6fsQnsWmbf7vC0JbGDcmIeHMQZnEt9B2d0MitH8MzY199c/SnziMOHjBWthLAlZ65L62HUQXvll8ZjQ72I/T045o/12loT1UNK+3BwW1XuuvaKa1zMZU5GMTfLBb6rZjCcNrorG/PrrSkI3maTHcATLmKtfNicYp5/bqs4+9cbJ+ARg36UTwFa9wWhjc1rCx147U3hfsJsHgU4Vi+flvQrCZ6+UAnXTTh/JeR8VONb9jpicqSrT+vYh5VphpbsIzXHu7Y9EGSAMRBFVkWrydspMYinb7Axstrm142ELtm+1dOilf1ZNswFeH/RBaDUHcFrgBtvNpE6+ITftXx5dyvROyukrY=
