language: java
sudo: true
before_install:
- chmod +x mvnw
deploy:
  provider: heroku
  api_key:
    secure: k9RSEYJWAP/wN7l7IMaV1qH2ehN953YtaZv8ZGkbegI6bBOM6Bl6lBTZY6Df/mXLCJ4S4m0WDYt6oI4hf5TW7lYbdQ6d/h1ssA27/Xg8H+xhjaySiSz9wiGGXDDwbBHWJ7qlP3n6IS6eZwpNUgxuGXa66Pnc7mPsdjVaV0goG/+nYQUEdms2UnPLRyzbU0FNEd2pffviMvR8UIcFo/7Tc0bVwHEKRYozIu33PybXpnsBrYYA7CgwZ2/ahKNLbPFLwvzg5WhZhDPupjB2yjQ8uaHKOirV33MHYkrdJ0E/8TFbfBnvI3dwjGd2N16t+PV24vISgx2zNlDXHcJFvbOW/kvYrWm8bi2HMeHvWK8E/QXXdE9OJ5Fv+9PNgiW7v2KTCYYYZWJvTVgqsTCkVmVPZO/zrF4/qX4WLJ+IQI6XH/U/WzYVNPIroVuTrDUUj8kAAo1HNxABU/8G5u7PlVHFTFDZSjLhqn+ktwtUlfuFqHiIQdRpCwBEMAuAmuFCHxmTlagZPbXZdc6BSiUfe1vUnXSAkblCd6xJDFBcsLNFwm7B6l0YZzIGvCEXlUDrcrfX4Xy/OBvTBFz20WCawhb06az1dl/w+MuNgtVh1dx+Gr7YLu/ohESQ0KRIsfgVlkLHDYvNe+yMNcVqKlmUHMqLyRdsFeW2yCUxU8Jq9O8TwHQ
  app: lit-basin-75485
